controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
boost_api:
  path: /api/boost
  controller: App\Controller\BoostController::generate
  methods: [POST]
